services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: panorama
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - panorama_net

  rabbitmq:
    image: rabbitmq:4.0.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - panorama_net

  api:
    image: alexsilvaro/desafio-panorama-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/panorama
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    networks:
      - panorama_net

  consumer:
    image: alexsilvaro/desafio-panorama-consumer
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/panorama
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - panorama_net

networks:
  panorama_net:
